work_dir: work_dir/ntu60/xsub/ctrgcn_joint/LT/rebuttal/2stage_training
ema: 0.9
weights: /mnt/netdisk/zhangjh/Code/CTR-GCN-main/work_dir/ntu60/xsub/ctrgcn_joint/LT/shapley_mix_logit_adjust_tem02/runs-83-0.808273184933584.pt
ignore_weights: [fc.bias, fc.weight]
#phase: test
start_epoch: 0
#naive_mix_epoch: 15
#naive_estimate_epoch: -1
# feeder
feeder: feeders.feeder_ntu.Feeder_LT_nosample
train_feeder_args:
  data_path: /mnt/netdisk/wulh/MAMP-main/data/ntu/NTU60_XSub.npz
  split: train
  vel: False
  bone: False
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  class_balance: True #class balance resampling, otherwise random over resampling
  p_interval: [0.5, 1]
  split_path: /mnt/netdisk/zhangjh/Code/BRL/data/NTU60_LT/NTU60_xsub_exp_100.txt
  train_id_path: /mnt/netdisk/zhangjh/Code/CTR-GCN-main/data/ntu/statistics/CS_train_id.txt
  sample_name_path: /mnt/netdisk/zhangjh/Code/CTR-GCN-main/data/ntu/statistics/skes_available_name.txt

test_feeder_args:
  data_path: /mnt/netdisk/wulh/MAMP-main/data/ntu/NTU60_XSub.npz
  split: test
  vel: False
  bone: False
  window_size: 64
  p_interval: [0.95]
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [60, 80]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 100
nesterov: True
